### ISSUE TITLE
Dependencies versions conflict: how to solve?

### ISSUE THREAD

**Issue by HereThereBeMonsters** [kserko/CineReel#2]
Hi, new to Dart and Flutter, and I am trying to run your app in order to learn about the BLoC pattern. Thanks for sharing it!

However, when I try to run the app, I run into the following error when getting the dependencies:

```
Running "flutter packages get" in CineReel...                    
Because every version of flutter_test from sdk depends on http 0.11.3+17 and cine_reel depends on http 0.12.0, flutter_test from sdk is forbidden.
So, because cine_reel depends on flutter_test any from sdk, version solving failed.
 
pub get failed (1)
```

The issue is descibed here: https://github.com/flutter/flutter/issues/21338

Did you also meet this problem and how did you solve it?

I cloned your repo today so I'm at the 1.3.4 tag, using Flutter 0.9.4 beta.

**Comment by HereThereBeMonsters** [comment]
So, I tried the solution suggested in the thread I linked. Switch to dev channel:
```
flutter channel dev
flutter doctor
```
That solved the problem :+1:

**Comment by kserko** [comment]
Hey good to hear you resolved that. Another trick when having dependency conflicts is to change all the version numbers in your pubspec.yaml file to `any`. If you then run `flutter pub get` again, flutter will auto-resolve the correct dependency versions. You can then go to your pubspec.lock file and take each specific version and copy it inside pubspec.yaml next to each dependency name
